#!/bin/bash
# .aidev/plugins/api-designer/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/REQ/Atomic.md"
OUTPUT_FILE="docs/CTR/OpenAPI.yaml"
PROMPT_DIR=".aidev/plugins/api-designer/prompts"

echo "🤖 api-designer (codex) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
# Codex/Other specific logic
echo "Exec: codex processing..."
cat "$INPUT_FILE" | codex_wrapper --instruction "$(cat $PROMPT_DIR/writer.md)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
claude --prompt "$(cat $PROMPT_DIR/reviewer.md) 
Context: 
$(cat $INPUT_FILE)
Draft:
$(cat $OUTPUT_FILE)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 api-designer Complete."
