#!/bin/bash
# .aidev/plugins/sysadmin/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/ADR/ADR.md"
OUTPUT_FILE="docs/SYS/Constraint.md"
PROMPT_DIR=".aidev/plugins/sysadmin/prompts"

echo "🤖 sysadmin (claude) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
claude --prompt "$(cat $PROMPT_DIR/writer.md) 
Context: 
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
gemini generate -t "$(cat $PROMPT_DIR/reviewer.md)
Context:
$(cat $INPUT_FILE)
Draft:
$(cat $OUTPUT_FILE)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 sysadmin Complete."
