"""Conformance: the CFB-PR-2 forward-coverage engine (gate + matrix + template rule).

Ties the engine to the spec contract at the conformance tier:

  * V5 — the generated ``TRACEABILITY_MATRIX.md`` regenerates byte-identically
    from the example corpus (deterministic + the committed copy is current).
  * The forward-coverage gate (``COV01``) blocks an in-scope FR that reaches no
    SPEC and stays silent on a fully-covered cascade (DD-6), and is gated to
    whole-corpus runs (DD-1).
  * The BRD template carries the normative FR-annotation rule (DD-3/DD-4) the
    authored-artifact form depends on.
"""

import sys
import unittest

from _spec import FRAMEWORK, REPO_ROOT, plugin_bundle_root

sys.path.insert(0, str(REPO_ROOT / "tools"))
sys.path.insert(0, str(plugin_bundle_root()))

from sdd_coverage import _collect_corpus, render_matrix  # noqa: E402
from sdd_doc_lint import _check_backward_coverage, _check_forward_coverage  # noqa: E402

_EXAMPLE_DOCS = REPO_ROOT / "examples" / "url-shortener" / "docs"
_MATRIX = _EXAMPLE_DOCS / "TRACEABILITY_MATRIX.md"


def _doc(doc_id: str, artifact_type: str, body: str) -> tuple[str, str]:
    return (
        f"{doc_id}.md",
        f"---\ndoc_id: {doc_id}\nartifact_type: {artifact_type}\n---\n\n{body}\n",
    )


class MatrixDeterminism(unittest.TestCase):
    def test_example_matrix_regenerates_byte_identical(self):
        # V5: the committed matrix must equal a fresh regeneration from the corpus.
        regenerated = render_matrix(_collect_corpus(_EXAMPLE_DOCS))
        committed = _MATRIX.read_text(encoding="utf-8")
        self.assertEqual(
            regenerated,
            committed,
            "examples/url-shortener/docs/TRACEABILITY_MATRIX.md is stale — "
            "regenerate with `python tools/sdd_coverage.py examples/url-shortener/docs`",
        )

    def test_matrix_is_marked_generated(self):
        self.assertIn("GENERATED by tools/sdd_coverage.py", _MATRIX.read_text(encoding="utf-8"))


class ForwardCoverageContract(unittest.TestCase):
    def _covered(self):
        order = ["BRD", "PRD", "EARS", "BDD", "ADR", "SPEC", "TDD", "IPLAN"]
        brd = _doc(
            "BRD-01",
            "BRD",
            "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** (P1): a thing.",
        )
        corpus = [brd]
        for i in range(1, len(order)):
            corpus.append(
                _doc(f"{order[i]}-01", order[i], f"@{order[i - 1].lower()}: {order[i - 1]}-01")
            )
        return corpus

    def test_fully_covered_cascade_has_no_cov01(self):
        self.assertEqual(_check_forward_coverage(self._covered()), [])

    def test_in_scope_fr_with_no_spec_blocks(self):
        corpus = [
            _doc(
                "BRD-01",
                "BRD",
                "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** (P1): x.",
            ),
            _doc("SPEC-99", "SPEC", "standalone"),
            _doc("IPLAN-99", "IPLAN", "standalone"),
        ]
        findings = _check_forward_coverage(corpus)
        self.assertEqual([(f.code, f.severity) for f in findings], [("COV01", "error")])

    def test_gated_to_whole_corpus_runs(self):
        # No SPEC/IPLAN in the corpus → the check no-ops (DD-1).
        brd = _doc(
            "BRD-01", "BRD", "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** (P1): x."
        )
        self.assertEqual(_check_forward_coverage([brd]), [])


class BackwardCoverageContract(unittest.TestCase):
    def test_example_corpus_has_no_cov02(self):
        # V6: every EARS/BDD doc in the corpus reaches a SPEC/TDD at doc level.
        corpus = _collect_corpus(_EXAMPLE_DOCS)
        cov2 = [f for f in _check_backward_coverage(corpus) if f.code == "COV02"]
        self.assertEqual(cov2, [], [f.message for f in cov2])

    def test_uncovered_requirement_doc_blocks_in_gate_code(self):
        corpus = [
            _doc("EARS-01", "EARS", "## 3. Requirements\n\n- EARS.01.03.aaaa: a req."),
            _doc("SPEC-99", "SPEC", "real spec, cites nothing"),
        ]
        findings = _check_backward_coverage(corpus, "gate-code")
        self.assertEqual([(f.code, f.severity) for f in findings], [("COV02", "error")])

    def test_gated_to_real_design_test_present(self):
        # No real (non-`-00`) SPEC/TDD → no-op (incl. a bare top-level-doc_id index).
        only_reqs = [_doc("EARS-01", "EARS", "## 3. Requirements\n\n- EARS.01.03.aaaa: a req.")]
        self.assertEqual(_check_backward_coverage(only_reqs), [])
        with_bare_index = only_reqs + [_doc("SPEC-00", "SPEC", "bare index")]
        self.assertEqual(_check_backward_coverage(with_bare_index), [])


class SPEC00CoverageSection(unittest.TestCase):
    def test_coverage_section_and_necessary_upstream_present(self):
        for base in (FRAMEWORK, plugin_bundle_root() / "framework"):
            tpl = (base / "layers" / "06_SPEC" / "SPEC-00_index.TEMPLATE.md").read_text(
                encoding="utf-8"
            )
            with self.subTest(copy=str(base)):
                self.assertIn("## Coverage", tpl)
                self.assertIn("COV02", tpl)
                self.assertIn("**Upstream (necessary)**: EARS, BDD, ADR", tpl)
                # the stale cumulative form is gone from the necessary-upstream line
                self.assertNotIn("**Upstream**: BRD, PRD, EARS, BDD, ADR", tpl)


class BRDTemplateRule(unittest.TestCase):
    def test_authored_fr_annotation_rule_present(self):
        for base in (FRAMEWORK, plugin_bundle_root() / "framework"):
            tpl = (base / "layers" / "01_BRD" / "BRD-TEMPLATE.yaml").read_text(encoding="utf-8")
            with self.subTest(copy=str(base)):
                self.assertIn("_authored_form", tpl)
                self.assertIn("Acceptance criteria:", tpl)
                self.assertIn("(P1|P2|Future", tpl)
                self.assertIn("realized_by", tpl)


if __name__ == "__main__":
    unittest.main()
