"""Conformance: the CFB-PR-2 forward-coverage engine (gate + matrix + template rule).

Ties the engine to the spec contract at the conformance tier:

  * V5 — the generated ``TRACEABILITY_MATRIX.md`` regenerates byte-identically
    from the example corpus (deterministic + the committed copy is current).
  * The forward-coverage gate (``COV01``) blocks an in-scope FR that reaches no
    SPEC and stays silent on a fully-covered cascade (DD-6), and is gated to
    whole-corpus runs (DD-1).
  * The BRD template carries the normative FR-annotation rule (DD-3/DD-4) the
    authored-artifact form depends on.
"""

import sys
import unittest

from _spec import FRAMEWORK, REPO_ROOT, plugin_bundle_root

sys.path.insert(0, str(REPO_ROOT / "tools"))
sys.path.insert(0, str(plugin_bundle_root()))

from sdd_coverage import _collect_corpus, render_matrix  # noqa: E402
from sdd_doc_lint import (  # noqa: E402
    _check_backward_coverage,
    _check_forward_coverage,
    _check_phase_leak,
    _check_ref_granularity,
)

_EXAMPLE_DOCS = REPO_ROOT / "examples" / "url-shortener" / "docs"
_MATRIX = _EXAMPLE_DOCS / "TRACEABILITY_MATRIX.md"


def _doc(doc_id: str, artifact_type: str, body: str) -> tuple[str, str]:
    return (
        f"{doc_id}.md",
        f"---\ndoc_id: {doc_id}\nartifact_type: {artifact_type}\n---\n\n{body}\n",
    )


class MatrixDeterminism(unittest.TestCase):
    def test_example_matrix_regenerates_byte_identical(self):
        # V5: the committed matrix must equal a fresh regeneration from the corpus.
        regenerated = render_matrix(_collect_corpus(_EXAMPLE_DOCS))
        committed = _MATRIX.read_text(encoding="utf-8")
        self.assertEqual(
            regenerated,
            committed,
            "examples/url-shortener/docs/TRACEABILITY_MATRIX.md is stale — "
            "regenerate with `python tools/sdd_coverage.py examples/url-shortener/docs`",
        )

    def test_matrix_is_marked_generated(self):
        self.assertIn("GENERATED by tools/sdd_coverage.py", _MATRIX.read_text(encoding="utf-8"))


class ForwardCoverageContract(unittest.TestCase):
    def _covered(self):
        # ELEMENT-COVERAGE-001: the PRD cites the BRD FR **element** (not the doc)
        # so element-level COV01 passes; the rest cite the upstream doc id.
        order = ["BRD", "PRD", "EARS", "BDD", "ADR", "SPEC", "TDD", "IPLAN"]
        brd = _doc(
            "BRD-01",
            "BRD",
            "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** (P1): a thing.",
        )
        corpus = [brd]
        for i in range(1, len(order)):
            up = order[i - 1]
            cite = "BRD.01.07.aaaa" if up == "BRD" else f"{up}-01"
            corpus.append(_doc(f"{order[i]}-01", order[i], f"@{up.lower()}: {cite}"))
        return corpus

    def test_fully_covered_cascade_has_no_cov01(self):
        self.assertEqual(_check_forward_coverage(self._covered()), [])

    def test_in_scope_fr_with_no_spec_blocks(self):
        # FR cited element-level by PRD (precedence (1) passes) but host reaches
        # no SPEC → the no-SPEC branch fires (ELEMENT-COVERAGE-001).
        corpus = [
            _doc(
                "BRD-01",
                "BRD",
                "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** (P1): x.",
            ),
            _doc("PRD-01", "PRD", "@brd: BRD.01.07.aaaa"),
            _doc("SPEC-99", "SPEC", "standalone"),
            _doc("IPLAN-99", "IPLAN", "standalone"),
        ]
        findings = _check_forward_coverage(corpus)
        self.assertEqual([(f.code, f.severity) for f in findings], [("COV01", "error")])
        self.assertIn("no SPEC", findings[0].message)

    def test_gated_to_whole_corpus_runs(self):
        # No SPEC/IPLAN in the corpus → the check no-ops (DD-1).
        brd = _doc(
            "BRD-01", "BRD", "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** (P1): x."
        )
        self.assertEqual(_check_forward_coverage([brd]), [])


class BackwardCoverageContract(unittest.TestCase):
    def test_example_corpus_cov02_surfaces_16_orphan_scenarios(self):
        # ELEMENT-COVERAGE-001: element-level COV02 surfaces the 16 orphaned BDD
        # scenarios (declared in BDD-01 but cited by no SPEC/TDD element) that the
        # prior doc-level gate could not see (the BDD doc reaches SPEC). They are
        # WARNINGS in `build` (corpus lint exit code unchanged) and ERRORS in
        # `gate-code`. All 26 EARS elements are realized (via BDD) so none are
        # flagged. Remediation of the orphans is a separate corpus/skill follow-up;
        # this codifies the known state so the gate stays meaningful.
        corpus = _collect_corpus(_EXAMPLE_DOCS)
        build = [f for f in _check_backward_coverage(corpus) if f.code == "COV02"]
        self.assertEqual(len(build), 16, [f.message for f in build])
        self.assertTrue(all(f.severity == "warning" for f in build))
        orphans = {f.message.split("'")[1] for f in build}
        self.assertTrue(all(o.startswith("BDD.") for o in orphans), orphans)
        gate = [f for f in _check_backward_coverage(corpus, "gate-code") if f.code == "COV02"]
        self.assertEqual(len(gate), 16)
        self.assertTrue(all(f.severity == "error" for f in gate))

    def test_uncovered_requirement_doc_blocks_in_gate_code(self):
        corpus = [
            _doc("EARS-01", "EARS", "## 3. Requirements\n\n- EARS.01.03.aaaa: a req."),
            _doc("SPEC-99", "SPEC", "real spec, cites nothing"),
        ]
        findings = _check_backward_coverage(corpus, "gate-code")
        self.assertEqual([(f.code, f.severity) for f in findings], [("COV02", "error")])

    def test_gated_to_real_design_test_present(self):
        # No real (non-`-00`) SPEC/TDD → no-op (incl. a bare top-level-doc_id index).
        only_reqs = [_doc("EARS-01", "EARS", "## 3. Requirements\n\n- EARS.01.03.aaaa: a req.")]
        self.assertEqual(_check_backward_coverage(only_reqs), [])
        with_bare_index = only_reqs + [_doc("SPEC-00", "SPEC", "bare index")]
        self.assertEqual(_check_backward_coverage(with_bare_index), [])


class RefGranularityContract(unittest.TestCase):
    def test_doc_level_ref_to_element_declaring_layer_blocks_in_gate_code(self):
        corpus = [
            _doc("EARS-01", "EARS", "- EARS.01.03.aaaa: a req."),
            _doc("BDD-01", "BDD", "@ears: EARS-01\nScenario."),
        ]
        findings = _check_ref_granularity(corpus, "gate-code")
        self.assertEqual([(f.code, f.severity) for f in findings], [("REFGRAN01", "error")])

    def test_element_level_and_spec_iplan_targets_are_silent(self):
        corpus = [
            _doc("EARS-01", "EARS", "- EARS.01.03.aaaa: a req."),
            _doc("BDD-01", "BDD", "@ears: EARS.01.03.aaaa\nScenario."),
            _doc("SPEC-01", "SPEC", "a spec"),
            _doc("TDD-01", "TDD", "@spec: SPEC-01\n- TDD.01.04.aaaa: a test."),
        ]
        self.assertEqual(_check_ref_granularity(corpus), [])


class TagSyntaxPage(unittest.TestCase):
    def test_tag_syntax_page_present_and_draws_the_boundary(self):
        for base in (FRAMEWORK, plugin_bundle_root() / "framework"):
            page = (base / "governance" / "TAG_SYNTAX.md").read_text(encoding="utf-8")
            with self.subTest(copy=str(base)):
                self.assertIn("REFGRAN01", page)
                # cross-refs the granularity authority (GD-03 / ID_NAMING), not duplicates
                self.assertIn("ID_NAMING_STANDARDS.md", page)
                self.assertIn("GD-03", page)
                # the carve-outs (self-tags + downstream pointers) are documented
                self.assertIn("Self-tag", page)


class SPEC00CoverageSection(unittest.TestCase):
    def test_coverage_section_and_necessary_upstream_present(self):
        for base in (FRAMEWORK, plugin_bundle_root() / "framework"):
            tpl = (base / "layers" / "06_SPEC" / "SPEC-00_index.TEMPLATE.md").read_text(
                encoding="utf-8"
            )
            with self.subTest(copy=str(base)):
                self.assertIn("## Coverage", tpl)
                self.assertIn("COV02", tpl)
                self.assertIn("**Upstream (necessary)**: EARS, BDD, ADR", tpl)
                # the stale cumulative form is gone from the necessary-upstream line
                self.assertNotIn("**Upstream**: BRD, PRD, EARS, BDD, ADR", tpl)


class BRDTemplateRule(unittest.TestCase):
    def test_authored_fr_annotation_rule_present(self):
        for base in (FRAMEWORK, plugin_bundle_root() / "framework"):
            tpl = (base / "layers" / "01_BRD" / "BRD-TEMPLATE.yaml").read_text(encoding="utf-8")
            with self.subTest(copy=str(base)):
                self.assertIn("_authored_form", tpl)
                self.assertIn("Acceptance criteria:", tpl)
                self.assertIn("(P1|P2|Future", tpl)
                self.assertIn("realized_by", tpl)


class PhaseLeakContract(unittest.TestCase):
    """COV03 (D54-F13 / D-0055) — a deferred (``Future``-banded) FR that IS
    realized downstream draws an advisory; the inverse of COV01's escape."""

    _FR = "## 7. Functional Requirements\n\n- **BRD.01.07.aaaa — F** ({band}): a thing."

    def _brd(self, band):
        return _doc("BRD-01", "BRD", self._FR.format(band=band))

    _PRD = _doc("PRD-01", "PRD", "@brd: BRD.01.07.aaaa")
    _PRD_NOCITE = _doc("PRD-01", "PRD", "no citation here")

    def test_deferred_fr_realized_downstream_warns(self):
        findings = _check_phase_leak([self._brd("Future"), self._PRD])
        self.assertEqual([(f.code, f.severity) for f in findings], [("COV03", "warning")])
        self.assertIn("phase-leak", findings[0].message)

    def test_deferred_fr_not_realized_is_silent(self):
        self.assertEqual(_check_phase_leak([self._brd("Future"), self._PRD_NOCITE]), [])

    def test_authored_fr_is_not_cov03(self):
        # A P1 (AUTHORED) FR is COV01's domain, never COV03.
        self.assertEqual(_check_phase_leak([self._brd("P1"), self._PRD]), [])

    def test_realized_by_fr_is_not_cov03(self):
        # `realized_by:` → REALIZED_BY (a positive coverage claim), never DEFERRED.
        self.assertEqual(_check_phase_leak([self._brd("Future, realized_by: ADR"), self._PRD]), [])

    def test_advisory_in_both_modes(self):
        # Never escalates to error, unlike COV01.
        for mode in ("build", "gate-code"):
            findings = _check_phase_leak([self._brd("Future"), self._PRD], mode=mode)
            self.assertEqual([f.severity for f in findings], ["warning"], mode)

    def test_runs_without_spec_or_iplan(self):
        # COV03 must NOT inherit COV01's {SPEC,IPLAN} corpus precondition — it
        # fires on a BRD+PRD-only corpus (the early-stage cascade).
        findings = _check_phase_leak([self._brd("Future"), self._PRD])
        self.assertEqual([f.code for f in findings], ["COV03"])


if __name__ == "__main__":
    unittest.main()
