#!/bin/bash
# .aidev/plugins/senior-dev/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/TASKS/Todo.md"
OUTPUT_FILE="src/main.py"
PROMPT_DIR=".aidev/plugins/senior-dev/prompts"

echo "🤖 senior-dev (claude) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
claude --prompt "$(cat $PROMPT_DIR/writer.md) 
Context: 
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
# Codex/Other specific logic
echo "Review: codex processing..."
cat "$OUTPUT_FILE" | codex_wrapper --instruction "$(cat $PROMPT_DIR/reviewer.md)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 senior-dev Complete."
