"""Conformance: no shipped dispatch reference is a bare roster name (#417).

`PREPROD-L7-BARE-DISPATCH`. The plugin's agents register under scoped
identifiers (`aidoc-flow:<name>`), so installing it cannot overwrite a
consumer's same-named agent. But Claude Code resolves a **bare** subagent
reference by scope precedence, in which the plugin's `agents/` directory ranks
lowest of five scopes — so a bare dispatch reference in the plugin's own
instructions routes to the *consumer's* agent on any machine that defines the
name, silently defeating the read-only review gates. PLUGIN-PREPROD-001 PR 4
(#418) *documented* the collision but renamed nothing — the scoped identifier
comes automatically from ``plugin.json``'s ``"name": "aidoc-flow"``, and
``agents/code-reviewer.md`` still declares ``name: code-reviewer``. So the
definitions were never the problem; this guard pins the *references*, which
documentation alone cannot keep closed (the bare names are read by the model,
not by the consumer).

Checked dispatch positions (the positions a model copies a `subagent_type`
value from):

* ``subagent_type=<name>`` / ``subagent_type: <name>`` literals, backticked or
  not, in the files named by ``DISPATCH_FILES`` below (``agents/*.md``,
  ``skills/*/SKILL.md``, ``commands/*.md``, ``README.md``, ``docs/AGENTS.md``) —
  *not* every shipped ``.md``;
* every non-first cell of a **dispatch table** — one whose header row names an
  agent/delegate column (``| Framework lens | Plugin agent |``,
  ``| Need | Delegate to |``, ``| Framework lens | Plugin agent | Agent file |``);
* any non-first table cell that is exactly one backticked roster name, in any
  table — a backstop for dispatch tables whose header this guard does not
  recognise;
* ``  `lens` → `agent` `` mappings **anywhere on a line**, not only in list
  items — `docs/AGENTS.md` states three of them mid-paragraph.

Keying on the *header* rather than on a column index is deliberate. An earlier
version of this guard matched only a row whose **last** cell was a backticked
roster name, so the plugin `README.md` lens→agent table — three columns, agent
in the **middle**, agent-file link last — was invisible to it: reverting a cell
there to the bare form passed the guard (mutation-measured, 2026-08-16). A
position-anchored rule silently under-covers the moment a table grows a column.

**Measured coverage, not asserted coverage.** 164 single-token reversions of a
scoped reference to its bare form: **145 killed, 19 survived (88%)**, against a
green baseline and a control mutant that the harness must kill before any of the
164 counts. Every one of the 19 survivors is a *descriptive* mention — the agent
as the subject of the sentence ("`aidoc-flow:pm-orchestrator` … is the
dispatcher"), an explanation of a lens binding ("the three lenses bound to
`aidoc-flow:solutions-architect`"), or consumer-facing naming advice. None is an
imperative that tells an engine to run an agent. That boundary is deliberate:
extending the prose rule to cover descriptive mentions flags the very paragraph
documenting the fix, which is a false positive a doc-only edit cannot resolve.
**So this guard pins dispatch positions, not every occurrence of a name** — do
not read a green run as "no bare roster name is reachable anywhere".

Definition names stay bare by design — an agent's own `name:` frontmatter,
its file name, roster inventories, and `docs/AGENTS.md`'s definition tables
document what a file *defines*, not what a dispatch resolves. The one-word
framework lens `synthesizer` (from `REVIEW_CREWS.yaml`, left column of a
mapping table) is likewise NOT a dispatch reference and must stay bare — which
is why cell 0 of every row is skipped.

**Known residue, deliberately out of scope.** The 51 lens playbooks under
`framework/playbooks/` carry a bare ``agent:`` frontmatter key. It is *not* a
plugin dispatch position: the plugin never *resolves* lens → agent from it —
that comes from the crew table in `skills/review-team/SKILL.md` — and GD-06
sanctions the key as an engine-defined executor a platform maps ("see the
platform's own docs"). Note the weaker claim: the key's text **is** read, since
the nine ``doc-*-audit`` skills inline whole playbook files (frontmatter
included) into each lens brief. It cannot become a dispatch because no recipient
declares the ``Task`` tool — only ``agents/pm-orchestrator.md`` does, and it is
never handed an inlined playbook. **If a lens agent is ever granted ``Task``,
revisit this exclusion.** It also
could not be scoped in the vendored copy even if it were — `framework/` is
byte-identical to the plugin bundle by conformance
(`test_plugin_framework_bundle.py`) and regenerated by
`tools/sync-plugin-framework.sh`. Named here so a future sweep does not read
this guard's silence on it as an oversight.
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

from _spec import REPO_ROOT

PLUGIN = REPO_ROOT / "platforms" / "claude-code-plugin"
PLUGIN_NAME = "aidoc-flow"
SCOPED_PREFIX = f"{PLUGIN_NAME}:"

# The eleven agent definition names (agents/*.md frontmatter `name`).
ROSTER = frozenset(
    {
        "pm-orchestrator",
        "requirements-analyst",
        "solutions-architect",
        "test-architect",
        "software-engineer",
        "devops-release-engineer",
        "code-reviewer",
        "security-engineer",
        "traceability-auditor",
        "chaos-engineer",
        "synthesizer",
    }
)

# Files whose dispatch positions this guard polices. Derived by glob, not by a
# hand list: a dispatch added to a *new* agent or command file must not arrive
# unguarded. The vendored ``framework/`` bundle is excluded by construction (it
# is byte-identical to canonical spec — see the module docstring).
DISPATCH_FILES = sorted(
    {
        *(PLUGIN / "agents").glob("*.md"),
        *(PLUGIN / "skills").glob("*/SKILL.md"),
        *(PLUGIN / "commands").glob("*.md"),
        PLUGIN / "README.md",
        PLUGIN / "docs" / "AGENTS.md",
    }
)

# `subagent_type=<name>` / `subagent_type: <name>`, backticked or not.
SUBAGENT_LITERAL = re.compile(r"subagent_type\s*[:=]\s*`?([a-z][a-z0-9-]*)")

# `lens` … → `agent` — words may sit between the lens and the arrow
# (```business_analyst` lens → `…```), and the pair may straddle a line
# break, so this is matched over a two-line window with whitespace collapsed.
ARROW_MAPPING = re.compile(r"`[^`]+`[^`|]{0,24}?→\s*`([a-z][a-z0-9:-]*)`")

# A verb that tells the engine to RUN an agent. Only a backticked roster name
# AFTER the verb counts — before it, the name is the sentence's subject and the
# line is describing the agent rather than dispatching it.
# This is the rule the table rules cannot express: the fixer step-6 defect and
# the review-team fan-in are prose, not table cells.
DISPATCH_VERB = re.compile(
    r"\b(dispatch(?:es|ed|ing)?|run(?:s|ning)?|spawn(?:s|ed|ing)?|"
    r"delegate(?:s|d)?|invoke(?:s|d)?|route(?:s|d)?)\b",
    re.IGNORECASE,
)

BACKTICKED = re.compile(r"`([a-z][a-z0-9:-]*)`")
LONE_BACKTICKED = re.compile(r"^`([a-z][a-z0-9:-]*)`$")

# A header row declaring an agent/delegate column. Only accepted as a header
# when the NEXT row is a delimiter row — otherwise a data row that merely
# mentions "agents" is misread as a header and skipped unscanned, which is how
# `README.md`'s roster-inventory row came to pass this guard for the wrong
# reason (measured 2026-08-16).
AGENT_COLUMN_HEADER = re.compile(r"\bagents?\b|\bdelegate", re.IGNORECASE)


def _cells(line: str) -> list[str] | None:
    """Split a markdown table row into cells, or None if it is not one."""
    stripped = line.strip()
    if not (stripped.startswith("|") and stripped.endswith("|")):
        return None
    return [c.strip() for c in stripped[1:-1].split("|")]


def _is_delimiter_row(cells: list[str] | None) -> bool:
    return bool(cells) and all(set(c) <= set("-: ") and "-" in c for c in cells)


def _violation(name: str, path: Path, lineno: int, kind: str) -> str:
    return f"{path.relative_to(REPO_ROOT)}:{lineno}: bare roster name `{name}` in {kind}"


class AgentDispatchScoping(unittest.TestCase):
    def test_no_bare_roster_name_in_dispatch_positions(self):
        """Every dispatch position uses the scoped `aidoc-flow:<name>` form."""
        violations: list[str] = []
        for path in DISPATCH_FILES:
            if not path.is_file():
                continue
            lines = path.read_text(encoding="utf-8").splitlines()
            rows = [_cells(line) for line in lines]
            in_dispatch_table = False
            for lineno, line in enumerate(lines, 1):
                cells = rows[lineno - 1]

                for m in SUBAGENT_LITERAL.finditer(line):
                    if m.group(1) in ROSTER:
                        violations.append(
                            _violation(m.group(1), path, lineno, "subagent_type literal")
                        )

                # Two-line window: an arrow and its target routinely straddle a
                # wrap, and a line-scoped rule silently covers only the pairs
                # that happen to fit on one line.
                window = line
                if lineno < len(lines):
                    window = f"{line} {lines[lineno]}"
                for m in ARROW_MAPPING.finditer(window):
                    if m.group(1) in ROSTER:  # a scoped name never equals a bare one
                        violations.append(
                            _violation(m.group(1), path, lineno, "lens→agent mapping")
                        )

                if cells is None:
                    in_dispatch_table = False  # a blank/prose line ends the table
                    # Prose dispatch: "run the `synthesizer` subagent over all
                    # slots". No bare name in a *cell*, so every table rule is
                    # blind to it — and an instruction with no identifier at
                    # all is the worst case, not the mildest.
                    # Only a name in OBJECT position — after the verb — is a
                    # dispatch. "The `pm-orchestrator` … delegates to the
                    # specialists" describes an agent; "run the `synthesizer`
                    # subagent" commands one, and only the second is capturable.
                    # Two-line window, for the same reason the arrow rule uses
                    # one: a numbered step routinely wraps between its verb and
                    # the agent it names.
                    # Blockquotes here are commentary — a note *describing*
                    # which surfaces dispatch is not itself a dispatch, and
                    # reading it as one flags the very paragraph that documents
                    # the fix.
                    verb = None if line.lstrip().startswith(">") else DISPATCH_VERB.search(window)
                    if verb:
                        for m in BACKTICKED.finditer(window, verb.end()):
                            if m.group(1) in ROSTER:
                                violations.append(
                                    _violation(m.group(1), path, lineno, "prose dispatch")
                                )
                    continue

                if _is_delimiter_row(cells):
                    continue
                if not in_dispatch_table and _is_delimiter_row(
                    rows[lineno] if lineno < len(rows) else None
                ):
                    if any(AGENT_COLUMN_HEADER.search(c) for c in cells):
                        in_dispatch_table = True
                        continue  # a header row names columns, not agents

                for idx, cell in enumerate(cells):
                    if idx == 0:
                        continue  # cell 0 is the framework lens, bare by design
                    lone = LONE_BACKTICKED.match(cell)
                    if lone:
                        if lone.group(1) in ROSTER:
                            violations.append(
                                _violation(lone.group(1), path, lineno, "mapping-table agent cell")
                            )
                    elif in_dispatch_table:
                        for m in BACKTICKED.finditer(cell):
                            if m.group(1) in ROSTER:
                                violations.append(
                                    _violation(
                                        m.group(1), path, lineno, "dispatch-table agent cell"
                                    )
                                )
        self.assertEqual(
            sorted(set(violations)),
            [],
            "bare-name dispatch references are silently capturable by a "
            "consumer's same-named agent (plugin scope ranks lowest); scope "
            f"them as `{SCOPED_PREFIX}<name>`:\n" + "\n".join(sorted(set(violations))),
        )

    def test_dispatch_tables_reference_the_scoped_form(self):
        """Positive control: the swept surfaces actually carry scoped cells.

        Guards against the check above passing vacuously (e.g. after a rename
        of every roster agent): each dispatch surface must contain at least one
        `aidoc-flow:<roster>` reference. `README.md` and `docs/AGENTS.md` are
        listed because they were reached by no rule before 2026-08-16 — a
        surface this guard does not actually read cannot fail it.
        """
        expected = {
            PLUGIN / "agents" / "pm-orchestrator.md": f"`{SCOPED_PREFIX}code-reviewer`",
            PLUGIN / "skills" / "review-team" / "SKILL.md": f"`{SCOPED_PREFIX}synthesizer`",
            PLUGIN / "README.md": f"`{SCOPED_PREFIX}test-architect`",
            PLUGIN / "docs" / "AGENTS.md": f"`{SCOPED_PREFIX}traceability-auditor`",
        }
        for path, token in expected.items():
            self.assertIn(
                token,
                path.read_text(encoding="utf-8"),
                f"{path.relative_to(REPO_ROOT)} lost its scoped dispatch references",
            )

    def test_every_fixer_resolves_its_mapped_agent_placeholder(self):
        """Step 4's `subagent_type=<mapped agent>` must resolve inside the file.

        Seven fixers carried a scoped `| Lens | Agent |` table; `doc-brd-fixer`
        and `doc-prd-fixer` carried none and named no substitute, so the
        placeholder resolved against nothing and a model filled it from the
        lens name — a bare agent, by the shortest path. A placeholder with no
        local map is the same defect class as prose with no identifier: there
        is no bare name for the rules above to find.
        """
        for path in sorted((PLUGIN / "skills").glob("doc-*-fixer/SKILL.md")):
            text = path.read_text(encoding="utf-8")
            if "<mapped agent>" not in text:
                continue
            self.assertIn(
                "| Lens | Agent |",
                text,
                f"{path.relative_to(REPO_ROOT)} dispatches `subagent_type=<mapped agent>` "
                "but carries no lens→agent table to resolve it",
            )

    def test_every_fixer_names_the_synthesizer_it_dispatches(self):
        """Each `doc-*-fixer` step 6 carries an identifier, not just prose.

        The nine fixers said only "Dispatch the synthesizer once" — no
        `subagent_type` at all, where their `doc-*-audit` counterparts carried
        one. Prose with no identifier is the worst case of the bug this guard
        exists to prevent: there is no bare name to find, so every rule above
        reads the file as clean while a model resolves the name by scope.
        """
        fixers = sorted((PLUGIN / "skills").glob("doc-*-fixer/SKILL.md"))
        self.assertEqual(len(fixers), 9, "expected 9 doc-*-fixer skills")
        for path in fixers:
            self.assertIn(
                f"`subagent_type={SCOPED_PREFIX}synthesizer`",
                path.read_text(encoding="utf-8"),
                f"{path.relative_to(REPO_ROOT)} dispatches the synthesizer in prose "
                "with no scoped identifier — a consumer's `synthesizer` wins",
            )


if __name__ == "__main__":
    unittest.main()
