#!/bin/bash
# .aidev/scripts/scaffold_swarm.sh
# Purpose: Generate the workflow.sh scripts for all 16 BMAD layers to ensure consistency.

BASE_DIR="/opt/data/docs_flow_framework/.aidev/plugins"
mkdir -p "$BASE_DIR"

# Function to create a workflow script
create_workflow() {
    role=$1
    input_file=$2
    output_file=$3
    executor=$4
    reviewer=$5
    executor_model=$6  # "claude" or "gemini" or "codex"
    reviewer_model=$7

    # Directory setup
    plugin_dir="$BASE_DIR/$role"
    mkdir -p "$plugin_dir/prompts"
    
    script_path="$plugin_dir/workflow.sh"
    
    # Don't overwrite if exists (to preserve custom logic)
    if [ -f "$script_path" ]; then
        echo "Skipping existing: $role"
        return
    fi
    
    echo "Generating workflow for: $role"

    # Write the script
    cat <<EOF > "$script_path"
#!/bin/bash
# .aidev/plugins/$role/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="$input_file"
OUTPUT_FILE="$output_file"
PROMPT_DIR=".aidev/plugins/$role/prompts"

echo "🤖 $role ($executor_model) starting..."
echo "   Reading: \$INPUT_FILE"
echo "   Target:  \$OUTPUT_FILE"

# 2. Execution Phase
EOF

    # Executor Logic
    if [ "$executor_model" == "claude" ]; then
        cat <<EOF >> "$script_path"
claude --prompt "\$(cat \$PROMPT_DIR/writer.md) 
Context: 
\$(cat \$INPUT_FILE)" > "\$OUTPUT_FILE"
EOF
    elif [ "$executor_model" == "gemini" ]; then
         cat <<EOF >> "$script_path"
gemini generate -t "\$(cat \$PROMPT_DIR/writer.md)
Context:
\$(cat \$INPUT_FILE)" > "\$OUTPUT_FILE"
EOF
    else
         cat <<EOF >> "$script_path"
# Codex/Other specific logic
echo "Exec: $executor_model processing..."
cat "\$INPUT_FILE" | codex_wrapper --instruction "\$(cat \$PROMPT_DIR/writer.md)" > "\$OUTPUT_FILE"
EOF
    fi

    cat <<EOF >> "$script_path"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
EOF

    # Reviewer Logic
    if [ "$reviewer_model" == "claude" ]; then
        cat <<EOF >> "$script_path"
claude --prompt "\$(cat \$PROMPT_DIR/reviewer.md) 
Context: 
\$(cat \$INPUT_FILE)
Draft:
\$(cat \$OUTPUT_FILE)" > "\$(dirname \$OUTPUT_FILE)/Review.md"
EOF
    elif [ "$reviewer_model" == "gemini" ]; then
         cat <<EOF >> "$script_path"
gemini generate -t "\$(cat \$PROMPT_DIR/reviewer.md)
Context:
\$(cat \$INPUT_FILE)
Draft:
\$(cat \$OUTPUT_FILE)" > "\$(dirname \$OUTPUT_FILE)/Review.md"
EOF
    else
         cat <<EOF >> "$script_path"
# Codex/Other specific logic
echo "Review: $reviewer_model processing..."
cat "\$OUTPUT_FILE" | codex_wrapper --instruction "\$(cat \$PROMPT_DIR/reviewer.md)" > "\$(dirname \$OUTPUT_FILE)/Review.md"
EOF
    fi

    cat <<EOF >> "$script_path"
echo "🚀 $role Complete."
EOF

    chmod +x "$script_path"
    
    # creating dummy prompts
    touch "$plugin_dir/prompts/writer.md"
    touch "$plugin_dir/prompts/reviewer.md"
}

# --- DEFINE THE SWARM ---
# Format: role input output executor reviewer executor_tool reviewer_tool

# Part 1: Planning
create_workflow "business-analyst"  "docs/init/notes.txt"     "docs/BRD/BRD.md"       "Gemini" "Claude" "gemini" "claude"
create_workflow "product-manager"   "docs/BRD/BRD.md"         "docs/PRD/PRD.md"       "Claude" "Gemini" "claude" "gemini"
create_workflow "requirements-eng"  "docs/PRD/PRD.md"         "docs/EARS/EARS.md"     "Gemini" "Codex"  "gemini" "codex"
create_workflow "qa-engineer"       "docs/EARS/EARS.md"       "docs/BDD/Features.feature" "Claude" "Codex" "claude" "codex"
create_workflow "architect"         "docs/BDD/Features.feature" "docs/ADR/ADR.md"     "Gemini" "Claude" "gemini" "claude"
create_workflow "sysadmin"          "docs/ADR/ADR.md"         "docs/SYS/Constraint.md" "Claude" "Gemini" "claude" "gemini"

# Part 2: Design
create_workflow "tech-analyst"      "docs/PRD/PRD.md"         "docs/REQ/Atomic.md"    "Gemini" "Claude" "gemini" "claude"
create_workflow "project-manager"   "docs/REQ/Atomic.md"      "docs/IMPL/Plan.md"     "Gemini" "Claude" "gemini" "claude"
create_workflow "api-designer"      "docs/REQ/Atomic.md"      "docs/CTR/OpenAPI.yaml" "Codex"  "Claude" "codex"  "claude"
create_workflow "tech-lead"         "docs/CTR/OpenAPI.yaml"   "docs/SPEC/Microspec.yaml" "Claude" "Gemini" "claude" "gemini"
create_workflow "eng-manager"       "docs/SPEC/Microspec.yaml" "docs/TASKS/Todo.md"   "Claude" "Gemini" "claude" "gemini"

# Part 3: Execution
create_workflow "senior-dev"        "docs/TASKS/Todo.md"      "src/main.py"           "Claude" "Codex"  "claude" "codex"
create_workflow "test-automation"   "src/main.py"             "tests/test_main.py"    "Codex"  "Claude" "codex"  "claude"
create_workflow "release-eng"       "tests/test_main.py"      "docs/VALID/Report.md"  "Gemini" "Claude" "gemini" "claude"
create_workflow "sre"               "docs/VALID/Report.md"    "docs/MAINT/Runbook.md" "Claude" "Gemini" "claude" "gemini"

echo "🎉 Full Swarm Scaffolded."
