#!/bin/bash
# .aidev/plugins/test-automation/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="src/main.py"
OUTPUT_FILE="tests/test_main.py"
PROMPT_DIR=".aidev/plugins/test-automation/prompts"

echo "🤖 test-automation (codex) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
# Codex/Other specific logic
echo "Exec: codex processing..."
cat "$INPUT_FILE" | codex_wrapper --instruction "$(cat $PROMPT_DIR/writer.md)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
claude --prompt "$(cat $PROMPT_DIR/reviewer.md) 
Context: 
$(cat $INPUT_FILE)
Draft:
$(cat $OUTPUT_FILE)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 test-automation Complete."
