#!/bin/bash
# .aidev/plugins/sre/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/VALID/Report.md"
OUTPUT_FILE="docs/MAINT/Runbook.md"
PROMPT_DIR=".aidev/plugins/sre/prompts"

echo "🤖 sre (claude) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
claude --prompt "$(cat $PROMPT_DIR/writer.md) 
Context: 
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
gemini generate -t "$(cat $PROMPT_DIR/reviewer.md)
Context:
$(cat $INPUT_FILE)
Draft:
$(cat $OUTPUT_FILE)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 sre Complete."
