# MVP Autopilot Configuration
# Version: 2.1
# Last Updated: 2026-01-13
# This file is auto-detected by mvp_autopilot.py unless overridden with --config

defaults:
  auto_fix: true
  mvp_validators: true
  report: markdown
  template_policy: mvp_only  # Framework uses MVP templates exclusively

# Template Configuration
# MVP templates are used exclusively. Full templates are deprecated and archived.
template_policy:
  mode: mvp_only
  deprecated_templates: archived/  # Full/section templates moved here

# Profile Configuration
profile:
  auto_fix: true
  strict: false
  mvp_validators: true
  report: markdown
  description: "Streamlined templates for rapid MVP development"
