#!/bin/bash
# .aidev/plugins/requirements-eng/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/PRD/PRD.md"
OUTPUT_FILE="docs/EARS/EARS.md"
PROMPT_DIR=".aidev/plugins/requirements-eng/prompts"

echo "🤖 requirements-eng (gemini) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
gemini generate -t "$(cat $PROMPT_DIR/writer.md)
Context:
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
echo "🚀 requirements-eng Complete."
