#!/usr/bin/env python3
"""
04_create_issues.py — Step 4: Create GitHub Issues from Remediation Actions

Reads the parsed remediation JSON and creates GitHub Issues for all actions
NOT already auto-applied. Integrates with the governance 4-Stage lifecycle:
  - P0 issues: created with ai:ready label (immediate AI pickup)
  - P1/P2 issues: created with ai:backlog label (sprint planning)

Post-creation:
  - Auto-generates IPLAN via generate_iplan_from_issue.py (if configured)
  - Assigns issue to GitHub Project Board (if GH_PROJECT is set)

Usage:
  python3 04_create_issues.py \\
    --actions <actions.json> \\
    --report <COUNCIL_AUDIT_REPORT.md> \\
    --doc-id <BRD-01> \\
    [--skip-applied]   # skip items where "applied": true
    [--dry-run]
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────
GH_REPO            = os.environ.get("GH_REPO", "")
GH_PROJECT         = os.environ.get("GH_PROJECT", "")
DRY_RUN            = os.environ.get("DRY_RUN", "false").lower() == "true"
CREATE_IPLAN       = os.environ.get("CREATE_IPLAN", "true").lower() == "true"

LABEL_REMEDIATION  = os.environ.get("GH_LABEL_REMEDIATION", "council:remediation")
LABEL_SOURCE       = os.environ.get("GH_LABEL_SOURCE", "source:council")

LABEL_BY_PRIORITY  = {
    "P0": "priority:P0",
    "P1": "priority:P1",
    "P2": "priority:P2",
    "P3": "priority:P3",
}
LIFECYCLE_BY_PRIORITY = {
    "P0": "ai:ready",      # immediate AI pickup
    "P1": "ai:backlog",
    "P2": "ai:backlog",
    "P3": "ai:backlog",
}

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def run(cmd: list[str], capture=False) -> tuple[int, str]:
    if DRY_RUN:
        print(f"  [DRY-RUN] Would run: {' '.join(cmd)}")
        return 0, ""
    result = subprocess.run(cmd, capture_output=capture, text=True)
    return result.returncode, result.stdout.strip() if capture else ""


def check_gh_cli():
    rc, _ = run(["gh", "--version"], capture=True)
    if rc != 0:
        print("[04_create_issues] ERROR: gh CLI not found. Install: https://cli.github.com/", file=sys.stderr)
        sys.exit(1)
    if not GH_REPO:
        print("[04_create_issues] ERROR: GH_REPO not set. Set it in your .env file.", file=sys.stderr)
        sys.exit(1)


def build_issue_body(action: dict, report_file: str, doc_id: str) -> str:
    report_link = Path(report_file).name
    return f"""## Remediation Task: {action['id']}

**Source**: AI Expert Council Audit of `{doc_id}`
**Report**: `{report_link}`
**Expert**: {action.get('source_expert', 'unknown')}
**Priority**: {action.get('priority', 'P2')}
**Action Type**: `{action.get('type', 'unknown')}`

---

## Description

{action.get('action', '')}

**Target Section**: `{action.get('target_section', 'unknown')}`
**Target Document**: `{action.get('target_document', doc_id)}`

---

## Acceptance Criteria

- [ ] {action.get('acceptance_criteria', 'Fix applied and document passes council review')}
- [ ] Document re-passes AI Expert Council audit with no P0/P1 findings on this issue
- [ ] PR created and merged to `main`

---

## Traceability

```
@council: {action['id']}
@brd: {doc_id}
@source: council:remediation
```

---
*Auto-generated by council_pipeline — Step 4 (04_create_issues.py)*
"""


def create_issue(action: dict, report_file: str, doc_id: str) -> str | None:
    """Create a GitHub Issue. Returns the issue number as string, or None on failure."""
    priority = action.get("priority", "P2")
    action_type = action.get("type", "unknown")
    action_id = action.get("id", "unknown")

    title = f"[COUNCIL-{action_id}] [{priority}] {action.get('action', '')[:80]}"
    body  = build_issue_body(action, report_file, doc_id)

    labels = [
        LABEL_REMEDIATION,
        LABEL_SOURCE,
        f"doc:{doc_id}",
        LABEL_BY_PRIORITY.get(priority, "priority:P2"),
        LIFECYCLE_BY_PRIORITY.get(priority, "ai:backlog"),
    ]

    cmd = [
        "gh", "issue", "create",
        "--repo", GH_REPO,
        "--title", title,
        "--body", body,
        "--label", ",".join(labels),
    ]

    if DRY_RUN:
        print(f"  [{action_id}] [DRY-RUN] Would run: {' '.join(cmd)}")
        return "https://github.com/dryrun/issues/999"

    print(f"  [{action_id}] Creating issue: {title[:70]}...")
    rc, stdout = run(cmd, capture=True)
    if rc != 0:
        print(f"  [{action_id}] ERROR creating issue (exit {rc})", file=sys.stderr)
        return None

    # Extract issue number from URL (e.g. https://github.com/owner/repo/issues/42)
    issue_url = stdout.strip()
    issue_num = issue_url.split("/")[-1] if "/" in issue_url else None
    print(f"  [{action_id}] Issue created: {issue_url}")
    return issue_num


def assign_to_project(issue_url: str):
    if not GH_PROJECT:
        return
    cmd = ["gh", "project", "item-add", GH_PROJECT, "--owner", "@me", "--url", issue_url]
    rc, _ = run(cmd)
    if rc == 0:
        print(f"  Assigned to project board #{GH_PROJECT}")


def generate_iplan(issue_num: str):
    """Call generate_iplan_from_issue.py if it exists."""
    if not CREATE_IPLAN or not issue_num:
        return

    # Find the script relative to this pipeline
    candidates = [
        Path(__file__).parents[4] / "governance/scripts/workflows/generate_iplan_from_issue.py",
        Path("/opt/data/docs_flow_framework/governance/scripts/workflows/generate_iplan_from_issue.py"),
    ]
    iplan_script = next((p for p in candidates if p.exists()), None)
    if not iplan_script:
        print(f"  [IPLAN] generate_iplan_from_issue.py not found — skipping")
        return

    cmd = ["python3", str(iplan_script), "--issue-number", issue_num, "--repo", GH_REPO]
    rc, _ = run(cmd)
    if rc == 0:
        print(f"  [IPLAN] Generated implementation plan for issue #{issue_num}")
    else:
        print(f"  [IPLAN] Warning: IPLAN generation failed for issue #{issue_num}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Create GitHub Issues from council remediation actions")
    parser.add_argument("--actions",      required=True, help="Path to actions.json from 01_parse.sh")
    parser.add_argument("--report",       required=True, help="Path to COUNCIL_AUDIT_REPORT.md")
    parser.add_argument("--doc-id",       required=True, help="Target document ID (e.g. BRD-01)")
    parser.add_argument("--skip-applied", action="store_true", help="Skip actions with applied=true")
    parser.add_argument("--dry-run",      action="store_true", help="Print actions without creating issues")
    args = parser.parse_args()

    global DRY_RUN
    DRY_RUN = DRY_RUN or args.dry_run

    if DRY_RUN:
        print("[04_create_issues] DRY-RUN mode — no issues will be created")

    check_gh_cli()

    with open(args.actions) as f:
        actions = json.load(f)

    if args.skip_applied:
        actions = [a for a in actions if not a.get("applied", False)]

    # Only create issues for non-auto-applicable types
    AUTO_TYPES = {"frontmatter_tag", "section_add", "matrix_row", "tag_correction", "dependency_add"}
    issue_actions = [a for a in actions if a.get("type") not in AUTO_TYPES]

    print(f"\n[04_create_issues] Creating {len(issue_actions)} issues (skipping {len(actions)-len(issue_actions)} auto-applied)...")

    created = 0
    failed  = 0

    for action in issue_actions:
        issue_url = create_issue(action, args.report, args.doc_id)
        if issue_url:
            issue_num = issue_url.split("/")[-1] if issue_url else None
            assign_to_project(issue_url or "")
            generate_iplan(issue_num or "")
            created += 1
        else:
            failed += 1

    print(f"\n[04_create_issues] Done: {created} issues created, {failed} failed")
    sys.exit(1 if failed > 0 and created == 0 else 0)


if __name__ == "__main__":
    main()
