#!/bin/bash
# .aidev/plugins/tech-analyst/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/PRD/PRD.md"
OUTPUT_FILE="docs/REQ/Atomic.md"
PROMPT_DIR=".aidev/plugins/tech-analyst/prompts"

echo "🤖 tech-analyst (gemini) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
gemini generate -t "$(cat $PROMPT_DIR/writer.md)
Context:
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
claude --prompt "$(cat $PROMPT_DIR/reviewer.md) 
Context: 
$(cat $INPUT_FILE)
Draft:
$(cat $OUTPUT_FILE)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 tech-analyst Complete."
