#!/bin/bash
# .aidev/plugins/qa-engineer/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="docs/EARS/EARS.md"
OUTPUT_FILE="docs/BDD/Features.feature"
PROMPT_DIR=".aidev/plugins/qa-engineer/prompts"

echo "🤖 qa-engineer (claude) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
claude --prompt "$(cat $PROMPT_DIR/writer.md) 
Context: 
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
echo "🚀 qa-engineer Complete."
