#!/usr/bin/env python3
"""sdd_coverage — generate the forward-coverage traceability matrix.

A thin reporter over the shared edge-graph core (CFB-PR-2 DD-7). It consumes
``build_edge_graph`` + the FR scanner + the ``covered_state`` classifier from
``sdd_doc_lint`` and emits a GENERATED, regenerable ``TRACEABILITY_MATRIX.md``:
for every gated BRD functional requirement, its band, ``covered_state``, and the
downstream layers its host BRD transitively reaches.

Document-level forward binding (a ✓ means the FR's *host BRD* reaches that
layer; PR-3 refines to element granularity). The matrix is the forward
companion to the backward walker ``trace_walk.py`` and the governance contract
``framework/governance/TRACEABILITY.md``.

Usage:
    sdd_coverage.py <docs_root> [--output PATH | -]

    <docs_root>      directory holding the SDD instance docs (e.g. .../docs).
    --output PATH    where to write (default: <docs_root>/TRACEABILITY_MATRIX.md);
                     ``-`` writes to stdout.

The output is deterministic (rows sorted by FR id) so a conformance gate can
regenerate and diff it. NEVER hand-edit the generated file — regenerate it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Shared engine (CFB-PR-2): the matrix and the linter's forward-coverage gate
# read the SAME graph + classifier, so they never disagree. `tools/` is
# sys.path[0] for a script run, so the package is importable here.
from sdd_doc_lint import (
    _artifact_code,
    _doc_forward_reach,
    _extract_frontmatter,
    build_edge_graph,
    covered_state_of,
    scan_fr_elements,
)
from sdd_doc_lint.trace_graph import KNOWN_LAYERS

#: The columns of the forward matrix — every layer downstream of BRD.
_DOWNSTREAM = tuple(layer for layer in KNOWN_LAYERS if layer != "BRD")

_GENERATED_BANNER = (
    "<!-- GENERATED by tools/sdd_coverage.py — DO NOT EDIT BY HAND.\n"
    "     Regenerate: python tools/sdd_coverage.py <docs_root> -->"
)


def _cell(value: str) -> str:
    """Escape a value for a Markdown table cell (a literal ``|`` would corrupt
    the row). FR ids / states cannot contain one; the band token theoretically
    can — defend anyway."""
    return value.replace("|", "\\|")


def render_matrix(corpus: list[tuple[str, str]]) -> str:
    """Render the forward-coverage matrix for ``corpus`` (list of
    ``(rel_path, text)``) as a deterministic Markdown string."""
    graph = build_edge_graph(corpus)

    rows: list[tuple[str, str, str, str, set[str]]] = []  # (fr_id, host, band, state, reached)
    for _rel, text in corpus:
        fm = _extract_frontmatter(text, _rel)
        if not fm:
            continue
        doc_id = str(fm.get("doc_id") or "").strip().strip('"').strip("'")
        # Identify the BRD exactly as the gate + graph do (_artifact_code), so
        # the matrix and the forward-coverage gate never list a different BRD
        # set — the shared-core invariant.
        if _artifact_code(fm) != "BRD" or not doc_id:
            continue
        reach = _doc_forward_reach(graph, doc_id)
        for fr in scan_fr_elements(text):
            rows.append((fr.elem_id, doc_id, fr.band or "—", covered_state_of(fr).value, reach))

    # Total order (fr_id, host) so duplicate fr ids across BRDs stay deterministic
    # regardless of input order.
    rows.sort(key=lambda r: (r[0], r[1]))

    out: list[str] = ["# Traceability Matrix — Forward Coverage", "", _GENERATED_BANNER, ""]
    out.append(
        "Document-level forward binding (CFB-PR-2 DD-7): a ✓ marks a layer the "
        "functional requirement's host BRD transitively reaches. PR-3 refines "
        "this to element granularity."
    )
    out.append("")
    if not rows:
        out.append("_No functional requirements found in this corpus._")
        return "\n".join(out) + "\n"

    header = ["FR", "Band", "State", *_DOWNSTREAM]
    out.append("| " + " | ".join(header) + " |")
    out.append("| " + " | ".join("---" for _ in header) + " |")
    for fr_id, _host, band, state, reach in rows:
        marks = ["✓" if layer in reach else "" for layer in _DOWNSTREAM]
        out.append("| " + " | ".join([_cell(fr_id), _cell(band), _cell(state), *marks]) + " |")

    full = sum(1 for _, _, _, _, reach in rows if {"SPEC", "IPLAN"} <= reach)
    out.append("")
    out.append(
        f"**Summary:** {len(rows)} functional requirement(s); {full} reach both SPEC and IPLAN."
    )
    return "\n".join(out) + "\n"


def _collect_corpus(docs_root: Path) -> list[tuple[str, str]]:
    corpus: list[tuple[str, str]] = []
    for p in sorted(docs_root.rglob("*")):
        if p.is_file() and p.suffix.lower() in (".md", ".yaml", ".yml"):
            corpus.append((p.relative_to(docs_root).as_posix(), p.read_text(encoding="utf-8")))
    return corpus


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="sdd_coverage")
    parser.add_argument("docs_root", type=Path, help="directory of SDD instance docs")
    parser.add_argument(
        "--output",
        default=None,
        help="output path (default: <docs_root>/TRACEABILITY_MATRIX.md; '-' = stdout)",
    )
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)

    if not args.docs_root.is_dir():
        print(f"sdd_coverage: not a directory: {args.docs_root}", file=sys.stderr)
        return 2

    matrix = render_matrix(_collect_corpus(args.docs_root))

    if args.output == "-":
        sys.stdout.write(matrix)
    else:
        out_path = Path(args.output) if args.output else args.docs_root / "TRACEABILITY_MATRIX.md"
        out_path.write_text(matrix, encoding="utf-8")
        print(f"sdd_coverage: wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
