#!/bin/bash
# .aidev/plugins/release-eng/workflow.sh
# Generated by scaffold_swarm.sh

# 1. Configuration
INPUT_FILE="tests/test_main.py"
OUTPUT_FILE="docs/VALID/Report.md"
PROMPT_DIR=".aidev/plugins/release-eng/prompts"

echo "🤖 release-eng (gemini) starting..."
echo "   Reading: $INPUT_FILE"
echo "   Target:  $OUTPUT_FILE"

# 2. Execution Phase
gemini generate -t "$(cat $PROMPT_DIR/writer.md)
Context:
$(cat $INPUT_FILE)" > "$OUTPUT_FILE"

echo "✅ Draft Generated. Starting Review..."

# 3. Review Phase
claude --prompt "$(cat $PROMPT_DIR/reviewer.md) 
Context: 
$(cat $INPUT_FILE)
Draft:
$(cat $OUTPUT_FILE)" > "$(dirname $OUTPUT_FILE)/Review.md"
echo "🚀 release-eng Complete."
